import type { User, Client, Lead, Campaign, ContentItem, Activity, Task, Notification } from './types'

// Team members
export const teamMembers: User[] = [
  {
    id: '1',
    name: 'Lucas Oliveira',
    email: 'lucas@connex.com.br',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
    role: 'Admin',
  },
  {
    id: '2',
    name: 'Marina Santos',
    email: 'marina@connex.com.br',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marina',
    role: 'Gestor',
  },
  {
    id: '3',
    name: 'Rafael Costa',
    email: 'rafael@connex.com.br',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rafael',
    role: 'Analista',
  },
  {
    id: '4',
    name: 'Juliana Ferreira',
    email: 'juliana@connex.com.br',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juliana',
    role: 'Gestor',
  },
  {
    id: '5',
    name: 'Pedro Almeida',
    email: 'pedro@connex.com.br',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro',
    role: 'Analista',
  },
]

// Clients
export const clients: Client[] = [
  {
    id: '1',
    name: 'TechStore Brasil',
    segment: 'E-commerce',
    status: 'Ativo',
    responsible: teamMembers[1],
    contractValue: 15000,
    lastActivity: new Date('2025-05-03'),
    onboardingDate: new Date('2024-06-15'),
    plan: 'Premium',
    contact: {
      email: 'contato@techstore.com.br',
      phone: '(11) 99999-1234',
      website: 'techstore.com.br',
    },
  },
  {
    id: '2',
    name: 'Restaurante Sabor & Arte',
    segment: 'Gastronomia',
    status: 'Ativo',
    responsible: teamMembers[2],
    contractValue: 5500,
    lastActivity: new Date('2025-05-04'),
    onboardingDate: new Date('2024-09-01'),
    plan: 'Standard',
    contact: {
      email: 'marketing@saborarte.com.br',
      phone: '(11) 98888-5678',
      website: 'saborarte.com.br',
    },
  },
  {
    id: '3',
    name: 'CloudFlow SaaS',
    segment: 'Tecnologia',
    status: 'Ativo',
    responsible: teamMembers[0],
    contractValue: 25000,
    lastActivity: new Date('2025-05-05'),
    onboardingDate: new Date('2024-03-10'),
    plan: 'Enterprise',
    contact: {
      email: 'growth@cloudflow.io',
      phone: '(11) 97777-9012',
      website: 'cloudflow.io',
    },
  },
  {
    id: '4',
    name: 'Beleza Natural',
    segment: 'Cosméticos',
    status: 'Lead',
    responsible: teamMembers[3],
    contractValue: 8000,
    lastActivity: new Date('2025-04-28'),
    onboardingDate: new Date('2025-04-20'),
    plan: 'Standard',
    contact: {
      email: 'comercial@belezanatural.com.br',
      phone: '(21) 96666-3456',
    },
  },
  {
    id: '5',
    name: 'Fitness Prime',
    segment: 'Academia',
    status: 'Em risco',
    responsible: teamMembers[1],
    contractValue: 4500,
    lastActivity: new Date('2025-04-15'),
    onboardingDate: new Date('2024-11-01'),
    plan: 'Basic',
    contact: {
      email: 'contato@fitnessprime.com.br',
      phone: '(11) 95555-7890',
      website: 'fitnessprime.com.br',
    },
  },
  {
    id: '6',
    name: 'Móveis Design',
    segment: 'Varejo',
    status: 'Ativo',
    responsible: teamMembers[4],
    contractValue: 12000,
    lastActivity: new Date('2025-05-02'),
    onboardingDate: new Date('2024-07-20'),
    plan: 'Premium',
    contact: {
      email: 'marketing@moveisdesign.com.br',
      phone: '(11) 94444-2345',
      website: 'moveisdesign.com.br',
    },
  },
  {
    id: '7',
    name: 'Escola Futuro',
    segment: 'Educação',
    status: 'Inativo',
    responsible: teamMembers[2],
    contractValue: 0,
    lastActivity: new Date('2025-02-10'),
    onboardingDate: new Date('2024-01-15'),
    plan: 'Standard',
    contact: {
      email: 'diretor@escolafuturo.edu.br',
      phone: '(11) 93333-6789',
    },
  },
  {
    id: '8',
    name: 'Pet Paradise',
    segment: 'Pet Shop',
    status: 'Ativo',
    responsible: teamMembers[3],
    contractValue: 6500,
    lastActivity: new Date('2025-05-04'),
    onboardingDate: new Date('2024-08-05'),
    plan: 'Standard',
    contact: {
      email: 'contato@petparadise.com.br',
      phone: '(11) 92222-0123',
      website: 'petparadise.com.br',
    },
  },
]

// Pipeline leads
export const leads: Lead[] = [
  // Atração
  {
    id: 'l1',
    companyName: 'Startup X',
    contactName: 'Carlos Silva',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    contractValue: 8000,
    daysInStage: 3,
    responsible: teamMembers[0],
    priority: 'high',
    stage: 'atracao',
  },
  {
    id: 'l2',
    companyName: 'Café Gourmet',
    contactName: 'Ana Paula',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    contractValue: 4500,
    daysInStage: 7,
    responsible: teamMembers[2],
    priority: 'medium',
    stage: 'atracao',
  },
  {
    id: 'l3',
    companyName: 'Academia Vida',
    contactName: 'Roberto Lima',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    contractValue: 5000,
    daysInStage: 1,
    responsible: teamMembers[1],
    priority: 'low',
    stage: 'atracao',
  },
  // Retenção
  {
    id: 'l4',
    companyName: 'Moda Express',
    contactName: 'Fernanda Costa',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda',
    contractValue: 12000,
    daysInStage: 5,
    responsible: teamMembers[3],
    priority: 'high',
    stage: 'retencao',
  },
  {
    id: 'l5',
    companyName: 'Tech Solutions',
    contactName: 'Marcos Oliveira',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcos',
    contractValue: 18000,
    daysInStage: 10,
    responsible: teamMembers[0],
    priority: 'high',
    stage: 'retencao',
  },
  // Adesão
  {
    id: 'l6',
    companyName: 'Clínica Saúde',
    contactName: 'Dr. Paulo Henrique',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Paulo',
    contractValue: 15000,
    daysInStage: 8,
    responsible: teamMembers[1],
    priority: 'high',
    stage: 'adesao',
  },
  {
    id: 'l7',
    companyName: 'Auto Peças Rio',
    contactName: 'José Santos',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jose',
    contractValue: 7000,
    daysInStage: 4,
    responsible: teamMembers[4],
    priority: 'medium',
    stage: 'adesao',
  },
  {
    id: 'l8',
    companyName: 'Farmácia Popular',
    contactName: 'Maria Clara',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    contractValue: 9500,
    daysInStage: 12,
    responsible: teamMembers[2],
    priority: 'medium',
    stage: 'adesao',
  },
  // Recompra
  {
    id: 'l9',
    companyName: 'TechStore Brasil',
    contactName: 'Bruno Ferreira',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruno',
    contractValue: 20000,
    daysInStage: 2,
    responsible: teamMembers[1],
    priority: 'high',
    stage: 'recompra',
  },
  {
    id: 'l10',
    companyName: 'CloudFlow SaaS',
    contactName: 'Ricardo Mendes',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ricardo',
    contractValue: 30000,
    daysInStage: 6,
    responsible: teamMembers[0],
    priority: 'high',
    stage: 'recompra',
  },
  // Indicação
  {
    id: 'l11',
    companyName: 'Móveis Design',
    contactName: 'Carla Souza',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carla',
    contractValue: 15000,
    daysInStage: 14,
    responsible: teamMembers[4],
    priority: 'medium',
    stage: 'indicacao',
  },
  {
    id: 'l12',
    companyName: 'Pet Paradise',
    contactName: 'Amanda Ribeiro',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    contractValue: 8000,
    daysInStage: 3,
    responsible: teamMembers[3],
    priority: 'low',
    stage: 'indicacao',
  },
  {
    id: 'l13',
    companyName: 'Escola Kids',
    contactName: 'Patrícia Gomes',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    contractValue: 6000,
    daysInStage: 9,
    responsible: teamMembers[2],
    priority: 'medium',
    stage: 'atracao',
  },
  {
    id: 'l14',
    companyName: 'Pizzaria Bella',
    contactName: 'Giovanni Rossi',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Giovanni',
    contractValue: 4000,
    daysInStage: 5,
    responsible: teamMembers[1],
    priority: 'low',
    stage: 'retencao',
  },
  {
    id: 'l15',
    companyName: 'Construtora ABC',
    contactName: 'Alberto Nunes',
    contactAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alberto',
    contractValue: 35000,
    daysInStage: 20,
    responsible: teamMembers[0],
    priority: 'high',
    stage: 'adesao',
  },
]

// Campaigns
export const campaigns: Campaign[] = [
  {
    id: 'c1',
    name: 'Black Friday 2025',
    client: clients[0],
    status: 'Ativa',
    platforms: ['Meta Ads', 'Google Ads', 'Instagram'],
    budget: { spent: 12500, total: 25000 },
    metrics: { impressions: 850000, clicks: 42500, ctr: 5.0, conversions: 1275 },
    responsible: teamMembers[1],
    startDate: new Date('2025-04-15'),
    endDate: new Date('2025-05-30'),
    objective: 'Aumentar vendas em 50%',
  },
  {
    id: 'c2',
    name: 'Lançamento Menu Primavera',
    client: clients[1],
    status: 'Ativa',
    platforms: ['Instagram', 'Meta Ads'],
    budget: { spent: 3200, total: 8000 },
    metrics: { impressions: 125000, clicks: 7500, ctr: 6.0, conversions: 450 },
    responsible: teamMembers[2],
    startDate: new Date('2025-04-20'),
    endDate: new Date('2025-05-20'),
    objective: 'Divulgar novo cardápio',
  },
  {
    id: 'c3',
    name: 'Captação B2B Q2',
    client: clients[2],
    status: 'Ativa',
    platforms: ['LinkedIn', 'Google Ads'],
    budget: { spent: 18000, total: 40000 },
    metrics: { impressions: 320000, clicks: 9600, ctr: 3.0, conversions: 288 },
    responsible: teamMembers[0],
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-06-30'),
    objective: 'Gerar 500 leads qualificados',
  },
  {
    id: 'c4',
    name: 'Dia das Mães',
    client: clients[5],
    status: 'Concluída',
    platforms: ['Meta Ads', 'Instagram', 'Google Ads'],
    budget: { spent: 15000, total: 15000 },
    metrics: { impressions: 450000, clicks: 22500, ctr: 5.0, conversions: 900 },
    responsible: teamMembers[4],
    startDate: new Date('2025-04-20'),
    endDate: new Date('2025-05-12'),
    objective: 'Campanha sazonal Dia das Mães',
  },
  {
    id: 'c5',
    name: 'Awareness Pet Care',
    client: clients[7],
    status: 'Pausada',
    platforms: ['Instagram', 'Meta Ads'],
    budget: { spent: 2800, total: 6000 },
    metrics: { impressions: 95000, clicks: 4750, ctr: 5.0, conversions: 190 },
    responsible: teamMembers[3],
    startDate: new Date('2025-04-10'),
    endDate: new Date('2025-05-10'),
    objective: 'Aumentar reconhecimento de marca',
  },
  {
    id: 'c6',
    name: 'Reativação de Clientes',
    client: clients[4],
    status: 'Rascunho',
    platforms: ['Meta Ads', 'Google Ads'],
    budget: { spent: 0, total: 5000 },
    metrics: { impressions: 0, clicks: 0, ctr: 0, conversions: 0 },
    responsible: teamMembers[1],
    startDate: new Date('2025-05-15'),
    endDate: new Date('2025-06-15'),
    objective: 'Recuperar clientes inativos',
  },
]

// Content calendar items
export const contentItems: ContentItem[] = [
  {
    id: 'ct1',
    client: clients[0],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Novidades em Eletrônicos',
    caption: 'Confira os lançamentos da semana!',
    publishDate: new Date('2025-05-05'),
    status: 'Publicado',
    responsible: teamMembers[2],
  },
  {
    id: 'ct2',
    client: clients[0],
    platform: 'Instagram',
    type: 'Stories',
    title: 'Unboxing iPhone',
    publishDate: new Date('2025-05-05'),
    status: 'Aprovado',
    responsible: teamMembers[2],
  },
  {
    id: 'ct3',
    client: clients[1],
    platform: 'Instagram',
    type: 'Reels',
    title: 'Preparo do Prato do Dia',
    caption: 'Veja como preparamos nosso risoto especial',
    publishDate: new Date('2025-05-06'),
    status: 'Aguardando aprovação',
    responsible: teamMembers[2],
  },
  {
    id: 'ct4',
    client: clients[2],
    platform: 'LinkedIn',
    type: 'Artigo',
    title: 'Tendências em Cloud Computing 2025',
    publishDate: new Date('2025-05-07'),
    status: 'Rascunho',
    responsible: teamMembers[0],
  },
  {
    id: 'ct5',
    client: clients[2],
    platform: 'Blog',
    type: 'Artigo',
    title: 'Como migrar para a nuvem',
    publishDate: new Date('2025-05-08'),
    status: 'Aprovado',
    responsible: teamMembers[0],
  },
  {
    id: 'ct6',
    client: clients[5],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Sofá modelo 2025',
    caption: 'Conheça nossa nova coleção',
    publishDate: new Date('2025-05-09'),
    status: 'Aprovado',
    responsible: teamMembers[4],
  },
  {
    id: 'ct7',
    client: clients[7],
    platform: 'Instagram',
    type: 'Stories',
    title: 'Dicas de cuidados com pets',
    publishDate: new Date('2025-05-10'),
    status: 'Rascunho',
    responsible: teamMembers[3],
  },
  {
    id: 'ct8',
    client: clients[0],
    platform: 'YouTube',
    type: 'Artigo',
    title: 'Review completo Galaxy S25',
    publishDate: new Date('2025-05-11'),
    status: 'Aguardando aprovação',
    responsible: teamMembers[2],
  },
  {
    id: 'ct9',
    client: clients[1],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Menu Executivo',
    caption: 'Opções especiais para o almoço',
    publishDate: new Date('2025-05-12'),
    status: 'Aprovado',
    responsible: teamMembers[2],
  },
  {
    id: 'ct10',
    client: clients[5],
    platform: 'Instagram',
    type: 'Reels',
    title: 'Tour pelo showroom',
    publishDate: new Date('2025-05-13'),
    status: 'Rascunho',
    responsible: teamMembers[4],
  },
  {
    id: 'ct11',
    client: clients[2],
    platform: 'LinkedIn',
    type: 'Feed',
    title: 'Case de sucesso: Empresa X',
    publishDate: new Date('2025-05-14'),
    status: 'Aprovado',
    responsible: teamMembers[0],
  },
  {
    id: 'ct12',
    client: clients[7],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Produtos para banho',
    caption: 'Deixe seu pet cheiroso',
    publishDate: new Date('2025-05-15'),
    status: 'Aguardando aprovação',
    responsible: teamMembers[3],
  },
  {
    id: 'ct13',
    client: clients[0],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Promoção relâmpago',
    publishDate: new Date('2025-05-16'),
    status: 'Rascunho',
    responsible: teamMembers[2],
  },
  {
    id: 'ct14',
    client: clients[1],
    platform: 'Instagram',
    type: 'Stories',
    title: 'Bastidores da cozinha',
    publishDate: new Date('2025-05-17'),
    status: 'Aprovado',
    responsible: teamMembers[2],
  },
  {
    id: 'ct15',
    client: clients[5],
    platform: 'Blog',
    type: 'Artigo',
    title: 'Tendências em decoração',
    publishDate: new Date('2025-05-18'),
    status: 'Rascunho',
    responsible: teamMembers[4],
  },
  {
    id: 'ct16',
    client: clients[2],
    platform: 'YouTube',
    type: 'Artigo',
    title: 'Webinar: Segurança em Cloud',
    publishDate: new Date('2025-05-20'),
    status: 'Aprovado',
    responsible: teamMembers[0],
  },
  {
    id: 'ct17',
    client: clients[7],
    platform: 'Instagram',
    type: 'Reels',
    title: 'Adoção responsável',
    publishDate: new Date('2025-05-22'),
    status: 'Rascunho',
    responsible: teamMembers[3],
  },
  {
    id: 'ct18',
    client: clients[0],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Comparativo de smartphones',
    publishDate: new Date('2025-05-25'),
    status: 'Rascunho',
    responsible: teamMembers[2],
  },
  {
    id: 'ct19',
    client: clients[1],
    platform: 'Instagram',
    type: 'Feed',
    title: 'Pratos veganos',
    publishDate: new Date('2025-05-28'),
    status: 'Rascunho',
    responsible: teamMembers[2],
  },
  {
    id: 'ct20',
    client: clients[5],
    platform: 'Instagram',
    type: 'Stories',
    title: 'Dicas de organização',
    publishDate: new Date('2025-05-30'),
    status: 'Rascunho',
    responsible: teamMembers[4],
  },
]

// Recent activities
export const activities: Activity[] = [
  {
    id: 'a1',
    type: 'novo_lead',
    description: 'Novo lead capturado: Startup X',
    timestamp: new Date('2025-05-05T14:30:00'),
    user: teamMembers[0],
  },
  {
    id: 'a2',
    type: 'reuniao',
    description: 'Reunião de briefing com CloudFlow SaaS',
    timestamp: new Date('2025-05-05T11:00:00'),
    user: teamMembers[0],
    client: clients[2],
  },
  {
    id: 'a3',
    type: 'contrato',
    description: 'Contrato assinado: Móveis Design - Upgrade Premium',
    timestamp: new Date('2025-05-04T16:45:00'),
    user: teamMembers[4],
    client: clients[5],
  },
  {
    id: 'a4',
    type: 'campanha',
    description: 'Campanha "Dia das Mães" finalizada com sucesso',
    timestamp: new Date('2025-05-04T10:00:00'),
    user: teamMembers[4],
    client: clients[5],
  },
  {
    id: 'a5',
    type: 'novo_lead',
    description: 'Novo lead capturado: Café Gourmet',
    timestamp: new Date('2025-05-03T09:15:00'),
    user: teamMembers[2],
  },
  {
    id: 'a6',
    type: 'reuniao',
    description: 'Call de acompanhamento com TechStore Brasil',
    timestamp: new Date('2025-05-02T15:00:00'),
    user: teamMembers[1],
    client: clients[0],
  },
]

// Tasks
export const tasks: Task[] = [
  {
    id: 't1',
    title: 'Finalizar proposta CloudFlow',
    dueDate: new Date('2025-05-06'),
    assignee: teamMembers[0],
    completed: false,
    priority: 'high',
  },
  {
    id: 't2',
    title: 'Revisar criativos Black Friday',
    dueDate: new Date('2025-05-07'),
    assignee: teamMembers[1],
    completed: false,
    priority: 'high',
  },
  {
    id: 't3',
    title: 'Agendar reunião com Beleza Natural',
    dueDate: new Date('2025-05-08'),
    assignee: teamMembers[3],
    completed: false,
    priority: 'medium',
  },
  {
    id: 't4',
    title: 'Atualizar relatório mensal',
    dueDate: new Date('2025-05-10'),
    assignee: teamMembers[2],
    completed: false,
    priority: 'medium',
  },
  {
    id: 't5',
    title: 'Contatar Fitness Prime (cliente em risco)',
    dueDate: new Date('2025-05-05'),
    assignee: teamMembers[1],
    completed: false,
    priority: 'high',
  },
]

// Notifications
export const notifications: Notification[] = [
  {
    id: 'n1',
    title: 'Novo lead',
    message: 'Startup X foi adicionado ao pipeline',
    timestamp: new Date('2025-05-05T14:30:00'),
    read: false,
    type: 'info',
  },
  {
    id: 'n2',
    title: 'Meta atingida!',
    message: 'Campanha Dia das Mães superou as conversões esperadas',
    timestamp: new Date('2025-05-04T10:00:00'),
    read: false,
    type: 'success',
  },
  {
    id: 'n3',
    title: 'Cliente em risco',
    message: 'Fitness Prime sem atividade há 20 dias',
    timestamp: new Date('2025-05-03T08:00:00'),
    read: true,
    type: 'warning',
  },
]

// KPI Data
export const kpiData = {
  totalClientes: 6,
  leadsNoPipeline: 15,
  campanhasAtivas: 3,
  faturamentoMes: 68500,
  clientesVariacao: 12.5,
  leadsVariacao: 8.3,
  campanhasVariacao: -25.0,
  faturamentoVariacao: 15.7,
}

// Pipeline data for chart
export const pipelineChartData = [
  { stage: 'Atração', count: 4, color: '#5B5FE8' },
  { stage: 'Retenção', count: 3, color: '#14B8A6' },
  { stage: 'Adesão', count: 4, color: '#8B5CF6' },
  { stage: 'Recompra', count: 2, color: '#22C55E' },
  { stage: 'Indicação', count: 2, color: '#F59E0B' },
]

// Monthly revenue data
export const revenueData = [
  { month: 'Jan', value: 52000, previous: 48000 },
  { month: 'Fev', value: 58000, previous: 51000 },
  { month: 'Mar', value: 61000, previous: 55000 },
  { month: 'Abr', value: 65000, previous: 59000 },
  { month: 'Mai', value: 68500, previous: 62000 },
]

// Channel performance data
export const channelData = [
  { channel: 'Meta Ads', leads: 45, conversions: 12, cost: 15000 },
  { channel: 'Google Ads', leads: 38, conversions: 10, cost: 12000 },
  { channel: 'Orgânico', leads: 25, conversions: 8, cost: 0 },
  { channel: 'Indicação', leads: 15, conversions: 6, cost: 0 },
]

// Funnel distribution
export const funnelData = [
  { name: 'Atração', value: 4, color: '#5B5FE8' },
  { name: 'Retenção', value: 3, color: '#14B8A6' },
  { name: 'Adesão', value: 4, color: '#8B5CF6' },
  { name: 'Recompra', value: 2, color: '#22C55E' },
  { name: 'Indicação', value: 2, color: '#F59E0B' },
]

// Client growth data
export const clientGrowthData = [
  { month: 'Jan', clients: 4 },
  { month: 'Fev', clients: 4 },
  { month: 'Mar', clients: 5 },
  { month: 'Abr', clients: 5 },
  { month: 'Mai', clients: 6 },
]
